apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: prod
bases:
  - ../../base
images:
  - name: <your-registry/your-image>
    newTag: <prod-tag>
configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
secretGenerator:
  - name: app-secret
    behavior: merge
    literals:
      - DB_PASSWORD=<prod-password>
