apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
spec:
  type: ClusterIP
  selector:
    app: simple-webapp
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
